remote_theme: jekyll/minima
minima:
  skin: solarized-light
plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
author:
  name: Alexander Sosnkowski
  email: "alexsosnkowski@gmail.com"
#titles_from_headings:
  #enabled:     true
  #strip_title: true
  #collections: true
header_pages:
  - title: Home
    url: /
  - title: Projects
    url: ./projects/projects.md
  - title: Test
    url: /test.md
#header_pages:
#  - projects.md
