remote_theme: daattali/beautiful-jekyll
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
author:
  name: Alexander Sosnkowski
  email: "alexsosnkowski@gmail.com"
#########################################################################################
##################################### Other Settings ####################################
#########################################################################################
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-titles-from-headings
#relative_links:
  #enabled: true
  #collections: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

header_pages:
  - title: Home
    url: /
  - title: Projects
    url: /projects/projects
  - title: Test
    url: /test
#header_pages:
#  - projects.md
