remote_theme: jekyll/minima
minima:
  skin: classic
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
author:
  name: Alexander Sosnkowski
  email: "alexsosnkowski@gmail.com"
header_pages:
  - index.md
  - test.md
  - projects.md

collections:
  - projects
